# Generated by Django 3.2.5 on 2021-07-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Time_take', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
